// Seeded Random Number Generator to ensure levels are consistent
class SeededRandom {
    constructor(seed) {
        this.seed = seed;
    }

    // Simple LCG algorithm
    next() {
        this.seed = (this.seed * 9301 + 49297) % 233280;
        return this.seed / 233280;
    }
}

const EDUCATIONAL_WORD_BANK = {
    primaria: {
        facil: [
            'PERA', 'UVA', 'MAIZ', 'SOL', 'RIO', 'FLOR', 'HOJA', 'PATO', 'GATO', 'PAN',
            'MIEL', 'LANA', 'PEZ', 'RANA', 'NUBE', 'LODO', 'PALA', 'CUBO', 'SACO', 'HENO',
            'POZO', 'CASA', 'PIÑA', 'COCO', 'LIMA', 'KIWI', 'HIGO', 'MORA', 'RAMA', 'RAIZ',
            'HUEVO', 'LECHE', 'TORO', 'AZUL', 'ROJO', 'PERRO', 'LUNA', 'MAR', 'AIRE', 'SOLO',
            'VACA', 'CHIVO', 'GALLO', 'POLLO', 'TRIGO', 'PAPA', 'AJO', 'NUEZ', 'VID', 'COL',
            'BUEY', 'COTO', 'DUNA', 'ERIZO', 'FOCA', 'GRIS', 'NIDO', 'OSO', 'PICO', 'RATA',
            'BOTA', 'LEÑA', 'VADO', 'POZA', 'LOMA', 'MATA', 'SETO', 'ZUMO', 'VINO', 'PULPA',
            'MESA', 'SILLA', 'PATIO', 'BARRO', 'TEJA', 'PUERTA', 'CERCA', 'MURO', 'PISO', 'TECHO',
            'NIEVE', 'HIELO', 'NIEBLA', 'RAYO', 'TRUENO', 'ROCIO', 'ESCARCHA', 'HELADA', 'BRISA', 'TORMENTA'
        ],
        medio: [
            'SEMILLA', 'RIEGO', 'ABONO', 'HUERTO', 'JARDIN', 'BOSQUE', 'CLIMA', 'SUELO', 'CANAL', 'PRESA',
            'MOLINO', 'SILO', 'CORRAL', 'PODA', 'BROTE', 'FRUTO', 'TALLO', 'SURCO', 'AZADA', 'RASTRILLO',
            'MANGO', 'LIMON', 'FRESA', 'CEREZA', 'CIRUELA', 'SANDIA', 'MELON', 'TRIGO', 'ARROZ', 'AVENA',
            'TOMATE', 'PEPINO', 'CEBOLLA', 'NARANJA', 'PLATANO', 'HUERTA', 'GRANJA', 'TRACTOR', 'ARADO', 'PASTO',
            'AVISPA', 'ABEJA', 'HORMIGA', 'ARAÑA', 'MOSCA', 'GRILLO', 'ORUGA', 'CAPULLO', 'POLEN', 'NECTAR',
            'BOSQUE', 'SELVA', 'DESIERTO', 'MONTAÑA', 'VALLE', 'LLANURA', 'COSTA', 'ISLA', 'ARRECIFE', 'PANTANO',
            'ZAPOTE', 'PITAYA', 'TUNA', 'NANCE', 'MAMEY', 'CARAMBOLA', 'CAMOTE', 'YUCA', 'JICAMA', 'RABANO',
            'NABO', 'APIO', 'ACELGA', 'ESPINACA', 'CILANTRO', 'PEREJIL', 'GRANERO', 'ESTANQUE', 'COBERTIZO', 'CISTERNA',
            'TINACO', 'MANGUERA', 'ASPERSOR', 'GOTERO', 'BOMBA', 'GALLINA', 'GANSO', 'CONEJO', 'MULA', 'POTRO'
        ],
        dificil: [
            'INJERTO', 'ESQUEJE', 'ALMACIGO', 'COMPOST', 'HUMUS', 'SUSTRATO', 'VIVERO', 'PARCELA', 'COSECHA', 'SIEMBRA',
            'PLAGA', 'HONGO', 'INSECTO', 'POLEN', 'ESTAMBRE', 'PISTILO', 'PETALO', 'SEPALO', 'CLOROFILA', 'SAVIA',
            'DURAZNO', 'GUAYABA', 'PAPAYA', 'PLATANO', 'NARANJA', 'TORONJA', 'CEBADA', 'CENTENO', 'SORGO', 'MIJO',
            'LOMBRICULTURA', 'HIDROPONIA', 'INVERNADERO', 'MICROTUNEL', 'FERTILIZANTE', 'PESTICIDA', 'FUNGICIDA', 'HERBICIDA', 'AGRONOMIA', 'EDAFOLOGIA',
            'ALFALFA', 'TREBOL', 'FORRAJE', 'SILO', 'HENO', 'ESTABLO', 'ORDEÑO', 'PASTOREO', 'VACUNACION', 'GENETICA',
            'BIODIVERSIDAD', 'ECOSISTEMA', 'SUSTENTABLE', 'RENOVABLE', 'ECOLOGIA', 'FOTOSINTESIS', 'TRANSPIRACION', 'RESPIRACION', 'NUTRICION', 'ABSORCION',
            'GERMINACION', 'POLINIZACION', 'FERTILIZACION', 'HIBRIDACION', 'CLONACION', 'APIARIO', 'AHUMADOR', 'EXTRACTOR', 'CERA', 'PROPOLEO',
            'JALEA', 'REINA', 'ZANGANO', 'OBRERA', 'SURCADOR', 'SEMBRADORA', 'CULTIVADORA', 'FUMIGADORA', 'COSECHADORA', 'EMPACADORA',
            'INOCUIDAD', 'CADENA', 'VALOR', 'PRECIO', 'COSTO', 'UTILIDAD', 'FINANZAS', 'CREDITO', 'INVERSION', 'RENTABILIDAD'
        ],
        experto: [
            'PYRUS_COMMUNIS', 'VITIS_VINIFERA', 'ZEA_MAYS', 'HELIANTHUS_ANNUUS', 'ROSA_CANINA', 'BETULA_PENDULA', 'QUERCUS_ROBUR', 'ANAS_PLATYRHYNCHOS', 'FELIS_CATUS', 'APIS_MELLIFERA',
            'MUSA_PARADISIACA', 'CITRUS_AURANTIUM', 'FRAGARIA_VESCA', 'PRUNUS_AVIUM', 'CITRULLUS_LANATUS', 'CUCUMIS_MELO', 'TRITICUM_DURUM', 'ORYZA_GLABERRIMA', 'AVENA_BYZANTINA', 'HORDEUM_SPONTANEUM',
            'SOLANUM_MELONGENA', 'CAPSICUM_FRUTESCENS', 'ALLIUM_PORRUM', 'DAUCUS_CAROTA', 'LACTUCA_SERRIOLA', 'BRASSICA_RAPA', 'MANGIFERA_INDICA', 'PERSEA_AMERICANA', 'COFFEA_CANEPHORA', 'THEOBROMA_BICOLOR',
            'SOLANUM_TUBEROSUM', 'PHASEOLUS_VULGARIS', 'TRITICUM_AESTIVUM', 'ORYZA_SATIVA', 'GLYCINE_MAX', 'HORDEUM_VULGARE', 'AVENA_SATIVA', 'SECALE_CEREALE', 'SORGHUM_BICOLOR', 'MEDICAGO_SATIVA',
            'SOLANUM_LYCOPERSICUM', 'CAPSICUM_ANNUUM', 'ALLIUM_CEPA', 'ALLIUM_SATIVUM', 'DAUCUS_CAROTA', 'LACTUCA_SATIVA', 'BRASSICA_OLERACEA', 'CUCUMIS_SATIVUS', 'CUCURBITA_PEPO', 'CITRULLUS_LANATUS',
            'MUSA_PARADISIACA', 'ANANAS_COMOSUS', 'MANGIFERA_INDICA', 'CITRUS_SINENSIS', 'CITRUS_LIMON', 'VITIS_VINIFERA', 'FRAGARIA_ANANASSA', 'RUBUS_IDAEUS', 'VACCINIUM_CORYMBOSUM', 'PERSEA_AMERICANA',
            'CARICA_PAPAYA', 'PSIDIUM_GUAJAVA', 'PRUNUS_DOMESTICA', 'PRUNUS_ARMENIACA', 'FICUS_CARICA', 'MORUS_NIGRA', 'PUNICA_GRANATUM', 'DIOSPYROS_KAKI', 'ERIOBOTRYA_JAPONICA', 'CYDONIA_OBLONGA',
            'ACTINIDIA_DELICIOSA', 'PASSIFLORA_EDULIS', 'ANNONA_MURICATA', 'ANNONA_SQUAMOSA', 'SYZYGIUM_CUMINI', 'ARTOCARPUS_HETEROPHYLLUS', 'LITCHI_CHINENSIS', 'DIMOCARPUS_LONGAN', 'NEPHELIUM_LAPPACEUM', 'DURIO_ZIBETHINUS'
        ]
    },
    secundaria: {
        facil: [
            'TRACTOR', 'GRANJA', 'CAMPO', 'ARADO', 'CULTIVO', 'SELVA', 'FAUNA', 'FLORA', 'AGUA', 'NORIA',
            'ESTABLO', 'GANADO', 'PASTOR', 'OBRERO', 'JORNAL', 'ZAFRA', 'TRUFA', 'SETA', 'ALGA', 'MUSGO',
            'NUEZ', 'ALMENDRA', 'AVELLANA', 'PISTACHO', 'CASTAÑA', 'DATIL', 'OLIVA', 'ACEITUNA', 'VID', 'PARRA',
            'LOMBRIS', 'TIERRA', 'RASTRA', 'SURCO', 'HUECO', 'MACETA', 'BALDE', 'REGARE', 'NIXTAMAL', 'ELOTE',
            'CHILE', 'CALABAZA', 'FRIJOL', 'VAINA', 'CASCARA', 'PULPA', 'JUGO', 'SABOR', 'COLOR', 'FORMA',
            'GRANO', 'SEMILLA', 'RAIZ', 'TALLO', 'HOJA', 'FLOR', 'FRUTO', 'POLEN', 'RAMA', 'TRONCO',
            'COSTAL', 'CANASTA', 'CAJA', 'CARRETA', 'YUGO', 'RIENDA', 'SILLA_DE_MONTAR', 'ESTRIBO', 'HERRADURA', 'CLAVO',
            'MARTILLO', 'SIERRA', 'HACHA', 'MACHETE', 'HOZ', 'GUADAÑA', 'PICO', 'BARRETA', 'PALA', 'AZADON'
        ],
        medio: [
            'AGRICULTOR', 'CAMPESINO', 'RANCHO', 'REBAÑO', 'MANADA', 'FAENA', 'INVERNADERO', 'ORGANICO', 'BIOLOGIA', 'QUIMICA',
            'AMBIENTE', 'RECURSO', 'SOLAR', 'EOLICA', 'BIOMASA', 'METANO', 'HIDROLOGIA', 'TOPOGRAFIA', 'MERCADO', 'COMERCIO',
            'LEGUMBRE', 'CEREAL', 'TUBERCULO', 'HORTALIZA', 'FRUTAL', 'FORRAJE', 'PASTO', 'PRADERA', 'DEHESA', 'MONTE',
            'SILVICULTURA', 'AGROECOLOGIA', 'PERMACULTURA', 'APICULTURA', 'ACUICULTURA', 'AVICULTURA', 'PORCICULTURA', 'CUNICULTURA', 'OVICULTURA', 'CAPRICULTURA',
            'MICROPROPAGACION', 'BIORREMEDIACION', 'FITOSANITARIO', 'INOCUIDAD', 'TRAZABILIDAD', 'LOGISTICA', 'CERTIFICACION', 'DENOMINACION', 'ORIGEN', 'PRODUCCION',
            'EXPORTACION', 'IMPORTACION', 'SUBSIDIO', 'CREDITO', 'ARANCEL', 'COOPERATIVA', 'ASOCIACION', 'DESARROLLO', 'SOSTENIBLE', 'RURAL',
            'BARBECHO', 'ROTACION', 'MONOCULTIVO', 'POLICULTIVO', 'INTERCALADO', 'ASOCIADO', 'ESCALONADO', 'SECUENCIAL', 'SIMULTANEO', 'MIXTO',
            'LABRANZA', 'MINIMA', 'CERO', 'CONSERVACION', 'CONVENCIONAL', 'PROFUNDA', 'SUPERFICIAL', 'VERTICAL', 'HORIZONTAL', 'CONTORNO'
        ],
        dificil: [
            'AGRONOMIA', 'PESTICIDA', 'FERTILIZANTE', 'ECOSISTEMA', 'SUSTENTABLE', 'BIODIVERSIDAD', 'GENETICA', 'BOTANICA', 'ZOOLOGIA', 'ECOLOGIA',
            'RENOVABLE', 'BIOCOMBUSTIBLE', 'ETANOL', 'BIODIESEL', 'LOMBRICULTURA', 'PERMACULTURA', 'AGROECOLOGIA', 'SILVICULTURA', 'AQUAPONIA', 'AEROPONIA',
            'FOTOPERIODO', 'VERNALIZACION', 'DORMANCIA', 'GERMINACION', 'VIABILIDAD', 'VIGOR', 'HIBRIDO', 'VARIEGACION', 'MUTACION', 'CLON',
            'FITOPATOLOGIA', 'ENTOMOLOGIA', 'EDAFOLOGIA', 'FISIOLOGIA', 'BIOQUIMICA', 'MICROBIOLOGIA', 'GENOMICA', 'PROTEOMICA', 'METABOLOMICA', 'BIOINFORMATICA',
            'HIDROPONIA', 'AQUAPONIA', 'AEROPONIA', 'HIDROPONIA', 'XEROJARDINERIA', 'AGROFORESTERIA', 'BIOTECNOLOGIA', 'NANOTECNOLOGIA', 'CRISPR', 'GENETICA',
            'METEOROLOGIA', 'CLIMATOLOGIA', 'HIDROLOGIA', 'GEOLOGIA', 'TOPOGRAFIA', 'CARTOGRAFIA', 'GEODESIA', 'FOTOGRAMETRIA', 'TELEDETECCION', 'SIG',
            'NEMATODO', 'ACARO', 'TRIPS', 'PULGON', 'MOSCA_BLANCA', 'MINADOR', 'BARRENADOR', 'GUSANO', 'LARVA', 'PUPA',
            'BACTERIA', 'VIRUS', 'FITOPLASMA', 'VIROIDE', 'MICOPLASMA', 'NEMATODO', 'PROTOZOO', 'ALGA', 'LIQUEN', 'MUSGO'
        ],
        experto: [
            'FOTOSINTESIS', 'HIDROPONIA', 'TRANSGENICO', 'METEOROLOGIA', 'CLIMATOLOGIA', 'GEOLOGIA', 'EDAFOLOGIA', 'CARTOGRAFIA', 'SOCIOLOGIA', 'ECONOMIA',
            'PHASEOLUS_LUNATUS', 'GLYCINE_MAX', 'SECALE_CEREALE', 'SORGHUM_BICOLOR', 'MEDICAGO_SATIVA', 'TRIFOLIUM_PRATENSE', 'LOLIUM_MULTIFLORUM', 'FESTUCA_RUBRA', 'DACTYLIS_GLOMERATA', 'PENNISETUM_PURPUREUM',
            'CYNODON_DACTYLON', 'AGAVE_AMERICANA', 'OPUNTIA_FICUS_INDICA', 'SACCHARUM_OFFICINARUM', 'GOSSYPIUM_HERBACEUM', 'ELAEIS_GUINEENSIS', 'COCOS_NUCIFERA', 'RICINUS_COMMUNIS', 'LINUM_USITATISSIMUM', 'CANNABIS_SATIVA',
            'MALUS_DOMESTICA', 'PYRUS_PYRIFOLIA', 'VITIS_LABRUSCA', 'PRUNUS_PERSICA', 'PRUNUS_DULCIS', 'CITRUS_SINENSIS', 'CITRUS_LIMON', 'FRAGARIA_ANANASSA', 'MUSA_ACUMINATA', 'PERSEA_GRATISSIMA',
            'SOLANUM_TUBEROSUM', 'PHASEOLUS_VULGARIS', 'TRITICUM_AESTIVUM', 'ORYZA_SATIVA', 'GLYCINE_SOJA', 'HORDEUM_VULGARE', 'AVENA_SATIVA', 'SECALE_MONTANUM', 'SORGHUM_SUDANENSE', 'ZEA_MEXICANA',
            'MEDICAGO_LUPULINA', 'TRIFOLIUM_REPENS', 'LOLIUM_PERENNE', 'FESTUCA_ARUNDINACEA', 'DACTYLIS_HISPANICA', 'PENNISETUM_CLANDESTINUM', 'BRACHIARIA_BRIZANTHA', 'PANICUM_MAXIMUM', 'CYNODON_PLECTOSTACHYUS', 'SORGHUM_HALEPENSE',
            'CUCURBITA_MAXIMA', 'CUCURBITA_MOSCHATA', 'CUCURBITA_PEPO', 'LAGENARIA_SICERARIA', 'LUFFA_AEGYPTIACA', 'MOMORDICA_CHARANTIA', 'SECHIUM_EDULE', 'BENINCASA_HISPIDA', 'TRICHOSANTHES_CUCUMERINA', 'CYCLANTHERA_PEDATA'
        ]
    },
    preparatoria: {
        facil: [
            'BIOTECNOLOGIA', 'AGROINDUSTRIA', 'FITOPATOLOGIA', 'MICROBIOLOGIA', 'POLINIZACION', 'ENTOMOLOGIA', 'NEMATOLOGIA', 'VIROLOGIA', 'BACTERIOLOGIA', 'MICOLOGIA',
            'FISIOLOGIA', 'ZOOTECNIA', 'VETERINARIA', 'AGRONEGOCIO', 'GESTION', 'PROYECTO', 'DESARROLLO', 'RURAL', 'URBANO', 'REGIONAL',
            'LENTEJA', 'GARBANZO', 'JUDIA', 'HABA', 'GUISANTE', 'SOJA', 'CACAHUETE', 'ALTRAMUZ', 'ALGARROBA', 'FENOGRECO',
            'SUELO', 'AGUA', 'AIRE', 'LUZ', 'CALOR', 'FRIO', 'VIENTO', 'LLUVIA', 'NIEVE', 'GRANIZO',
            'ARBOL', 'ARBUSTO', 'HIERBA', 'MATA', 'RAIZ', 'TALLO', 'HOJA', 'FLOR', 'FRUTO', 'SEMILLA',
            'VACA', 'OVEJA', 'CABRA', 'CERDO', 'POLLO', 'PATO', 'GANSO', 'PAVO', 'CABALLO', 'BURRO',
            'QUINOA', 'AMARANTO', 'CHIA', 'LINAZA', 'SESAMO', 'GIRASOL', 'CARTAMO', 'COLZA', 'MOSTAZA', 'CANOLA',
            'ESTIERCOL', 'GALLINAZA', 'PORQUINAZA', 'BOVINAZA', 'CAPRINAZA', 'OVINAZA', 'EQUINAZA', 'CUNIAZA', 'PALOMINA', 'MURCIELAGUINA'
        ],
        medio: [
            'ADMINISTRACION', 'PLANIFICACION', 'EVALUACION', 'NACIONAL', 'GLOBAL', 'COMUNITARIO', 'LEGISLACION', 'NORMATIVA', 'CERTIFICACION', 'CALIDAD',
            'INOCUIDAD', 'TRAZABILIDAD', 'LOGISTICA', 'SUMINISTRO', 'VALOR', 'MERCADOTECNIA', 'FINANZA', 'INVERSION', 'CREDITO', 'SUBSIDIO',
            'NITROGENO', 'FOSFORO', 'POTASIO', 'CALCIO', 'MAGNESIO', 'AZUFRE', 'HIERRO', 'ZINC', 'BORO', 'COBRE',
            'MANGANESO', 'MOLIBDENO', 'CLORO', 'NIQUEL', 'SILICIO', 'SODIO', 'COBALTO', 'VANADIO', 'SELENIO', 'YODO',
            'FOTOSINTESIS', 'RESPIRACION', 'TRANSPIRACION', 'NUTRICION', 'ABSORCION', 'TRANSLOCACION', 'METABOLISMO', 'ENZIMA', 'HORMONA', 'AUXINA',
            'GIBERELINA', 'CITOCININA', 'ETILENO', 'ABSCISICO', 'FLORACION', 'FRUCTIFICACION', 'MADURACION', 'SENESCENCIA', 'ABSCISION', 'DORMANCIA',
            'VERMICOMPOST', 'BOCASHI', 'BIOL', 'SUPERMAGRO', 'CALDOS_MINERALES', 'TE_COMPOST', 'MICROORGANISMOS', 'TRICHODERMA', 'BACILLUS', 'AZOSPIRILLUM',
            'RHIZOBIUM', 'MICORRIZAS', 'AZOTOBACTER', 'PSEUDOMONAS', 'BEAUVERIA', 'METARHIZIUM', 'PAECILOMYCES', 'LECANICILLIUM', 'ISARIA', 'NOMURAEA'
        ],
        dificil: [
            'FITOMEJORAMIENTO', 'BIOINGENIERIA', 'DASONOMIA', 'ACUICULTURA', 'CULTIVO_VERTICAL', 'HIDROGEOLOGIA', 'AGROMETEOROLOGIA', 'PALEOCLIMATOLOGIA', 'PETROLOGIA', 'PEDOLOGIA',
            'GEODESIA', 'FOTOGRAMETRIA', 'GEOMORFOLOGIA', 'ANTROPOLOGIA', 'MACROECONOMIA', 'MICROECONOMIA', 'OLIGOPOLIO', 'EXPORTACION', 'MANUFACTURA', 'INNOVACION',
            'XILEMA', 'FLOEMA', 'ESTOMA', 'TRICOMA', 'CUTICULA', 'EPIDERMIS', 'PARENQUIMA', 'MERISTEMO', 'CAMBIUM', 'PERIDERMIS',
            'COLENQUIMA', 'ESCLERENQUIMA', 'ENDODERMIS', 'PERICICLO', 'VASICENTRICO', 'ANFIVASAL', 'ANFIBRIAL', 'PROTOXILEMA', 'METAXILEMA', 'PROTOFLOEMA',
            'METAFLOEMA', 'TRAQUEIDA', 'ELEMENTO_VASO', 'TUBO_CRIBOSO', 'CELULA_ACOMPAÑANTE', 'RADIO_MEDULAR', 'LENTICELA', 'RITIDOMA', 'FELEMA', 'FELODERMIS',
            'TEJIDO_ADIPOSO', 'TEJIDO_EPITELIAL', 'TEJIDO_MUSCULAR', 'TEJIDO_NERVIOSO', 'TEJIDO_CONECTIVO', 'TEJIDO_OSEO', 'TEJIDO_SANGUINEO', 'TEJIDO_LINFATICO', 'TEJIDO_CARTILAGINOSO', 'TEJIDO_AREOLAR',
            'FITOCROMO', 'CRIPTOCROMO', 'FOTOTROPINA', 'ZEITLUPE', 'BRASSINOSTEROIDES', 'JASMONATOS', 'SALICILATOS', 'POLIAMINAS', 'PEPTIDOS', 'OLIGOSACARINAS',
            'ELICITORES', 'QUITINASAS', 'GLUCANASAS', 'PEROXIDASAS', 'CATALASAS', 'SUPEROXIDO_DISMUTASA', 'ASCORBATO_PEROXIDASA', 'GLUTATIONA_REDUCTASA', 'DEHIDROASCORBATO', 'MONODEHIDROASCORBATO'
        ],
        experto: [
            'MICROPROPAGACION', 'BIOINFORMATICA', 'GENOMICA', 'PROTEOMICA', 'METABOLOMICA', 'EPIGENETICA', 'NANOTECNOLOGIA', 'BIOREMEDIACION', 'FITOREMEDIACION', 'XENOBIOTICO',
            'SOLANUM_TUBEROSUM', 'PHASEOLUS_VULGARIS', 'TRITICUM_AESTIVUM', 'ORYZA_SATIVA', 'GLYCINE_SOJA', 'HORDEUM_VULGARE', 'AVENA_SATIVA', 'SECALE_MONTANUM', 'SORGHUM_SUDANENSE', 'ZEA_MEXICANA',
            'MALUS_DOMESTICA', 'PYRUS_PYRIFOLIA', 'VITIS_LABRUSCA', 'PRUNUS_PERSICA', 'PRUNUS_DULCIS', 'CITRUS_SINENSIS', 'CITRUS_LIMON', 'FRAGARIA_ANANASSA', 'MUSA_ACUMINATA', 'PERSEA_GRATISSIMA',
            'ANANAS_COMOSUS', 'MANGIFERA_FOETIDA', 'THEOBROMA_CACAO', 'COFFEA_ARABICA', 'SACCHARUM_SPONTANEUM', 'GOSSYPIUM_HIRSUTUM', 'HELIANTHUS_TUBEROSUS', 'BRASSICA_NAPUS', 'ELAEIS_OLEIFERA', 'COCOS_CAPITATA',
            'CRISPR_CAS9', 'TRANSCRIPTOMICA', 'INTERACTOMICA', 'FLUXOMICA', 'FENOMICA', 'QUIMIOMETRIA', 'BIOESTADISTICA', 'GEOESTADISTICA', 'ECONOMETRIA', 'PSICOMETRIA',
            'MEDICAGO_LUPULINA', 'TRIFOLIUM_REPENS', 'LOLIUM_PERENNE', 'FESTUCA_ARUNDINACEA', 'DACTYLIS_HISPANICA', 'PENNISETUM_CLANDESTINUM', 'BRACHIARIA_BRIZANTHA', 'PANICUM_MAXIMUM', 'CYNODON_PLECTOSTACHYUS', 'SORGHUM_HALEPENSE',
            'CHENOPODIUM_QUINOA', 'AMARANTHUS_CAUDATUS', 'SALVIA_HISPANICA', 'LINUM_USITATISSIMUM', 'SESAMUM_INDICUM', 'HELIANTHUS_ANNUUS', 'CARTHAMUS_TINCTORIUS', 'BRASSICA_NAPUS', 'SINAPIS_ALBA', 'BRASSICA_JUNCEA',
            'LUPINUS_ALBUS', 'LUPINUS_ANGUSTIFOLIUS', 'LUPINUS_LUTEUS', 'LUPINUS_MUTABILIS', 'VICIA_FABA', 'PISUM_SATIVUM', 'LENS_CULINARIS', 'CICER_ARIETINUM', 'VIGNA_UNGUICULATA', 'VIGNA_RADIATA'
        ]
    },
    universidad: {
        facil: [
            'INVESTIGACION', 'CIENCIA', 'TEORIA', 'METODO', 'ANALISIS', 'SINTESIS', 'HIPOTESIS', 'VARIABLE', 'MUESTRA', 'DATO',
            'ESTADISTICA', 'PROBABILIDAD', 'MODELO', 'SIMULACION', 'OPTIMIZACION', 'SISTEMA', 'COMPLEJIDAD', 'DINAMICA', 'EVOLUCION', 'ADAPTACION',
            'BROCOLI', 'COLIFLOR', 'REPOLLO', 'RABANO', 'NABO', 'RUCULA', 'BERRO', 'MOSTAZA', 'WASABI', 'RABANO_PICANTE',
            'ZANAHORIA', 'TOMATE', 'PEPINO', 'CEBOLLA', 'NARANJA', 'PLATANO', 'HUERTA', 'GRANJA', 'TRACTOR', 'ARADO',
            'VACA', 'OVEJA', 'CABRA', 'CERDO', 'POLLO', 'PATO', 'GANSO', 'PAVO', 'CABALLO', 'BURRO',
            'TULIPAN', 'ROSA', 'GIRASOL', 'LIRIO', 'MARGARITA', 'ORQUIDEA', 'CLAVEL', 'GERANIO', 'PETUNIA', 'BEGONIA',
            'AGUACATE', 'CACAO', 'CAFE', 'VAINILLA', 'CANELA', 'PIMIENTA', 'JENGIBRE', 'CURCUMA', 'AZAFRAN', 'CARDAMOMO',
            'CLAVO', 'NUEZ_MOSCADA', 'ANIS', 'COMINO', 'OREGANO', 'TOMILLO', 'ROMERO', 'ALBAHACA', 'MENTA', 'HIERBABUENA'
        ],
        medio: [
            'EPISTEMOLOGIA', 'PARADIGMA', 'ONTOLOGIA', 'METODOLOGIA', 'HERMENEUTICA', 'DIALECTICA', 'FENOMENOLOGIA', 'ESTRUCTURALISMO', 'FUNCIONALISMO', 'PRAGMATISMO',
            'ETICA', 'BIOETICA', 'DEONTOLOGIA', 'AXIOLOGIA', 'ESTETICA', 'LOGICA', 'RETORICA', 'FILOSOFIA', 'POLITICA', 'DERECHO',
            'FOSFORILACION', 'GLUCOLISIS', 'CICLO_KREBS', 'OXIDACION', 'REDUCCION', 'CATALISIS', 'ENZIMOLOGIA', 'CINETICA', 'TERMODINAMICA', 'ENTROPIA',
            'ENTALPIA', 'ENERGIA_LIBRE', 'CINETICA_QUIMICA', 'EQUILIBRIO_QUIMICO', 'ELECTROQUIMICA', 'QUIMICA_ORGANICA', 'QUIMICA_INORGANICA', 'QUIMICA_ANALITICA', 'FISICOQUIMICA', 'BIOQUIMICA',
            'GENETICA_MOLECULAR', 'GENETICA_POBLACIONES', 'GENETICA_CUANTITATIVA', 'GENETICA_EVOLUTIVA', 'GENETICA_DESARROLLO', 'CITOGENETICA', 'EPIGENETICA', 'GENOMICA', 'PROTEOMICA', 'METABOLOMICA',
            'MICROBIOLOGÍA_AGRÍCOLA', 'MICROBIOLOGÍA_INDUSTRIAL', 'MICROBIOLOGÍA_AMBIENTAL', 'MICROBIOLOGÍA_MÉDICA', 'VIROLOGÍA', 'BACTERIOLOGÍA', 'MICOLOGÍA', 'PARASITOLOGÍA', 'INMUNOLOGÍA', 'EPIDEMIOLOGÍA',
            'CROMATOGRAFIA', 'ESPECTROSCOPIA', 'ESPECTROMETRIA', 'RESONANCIA_MAGNETICA', 'DIFRACCION', 'FLUORESCENCIA', 'LUMINISCENCIA', 'ABSORBANCIA', 'TRANSMITANCIA', 'REFLECTANCIA',
            'CENTRIFUGACION', 'FILTRACION', 'DESTILACION', 'CRISTALIZACION', 'PRECIPITACION', 'EXTRACCION', 'PURIFICACION', 'SEPARACION', 'CONCENTRACION', 'DILUC ION'
        ],
        dificil: [
            'TRANSDISCIPLINA', 'INTERDISCIPLINA', 'MULTIDISCIPLINA', 'HOLISMO', 'REDUCCIONISMO', 'EMERGENCIA', 'AUTOPOIESIS', 'CIBERNETICA', 'SEMIOTICA', 'ANTROPOCENO',
            'RESILIENCIA', 'VULNERABILIDAD', 'SOSTENIBILIDAD', 'REGENERACION', 'AGRICULTURA_ORGANICA', 'BIOAGRICULTURA', 'ETNOBOTANICA', 'ETNOECOLOGIA', 'BIOMIMETICA', 'BIONICA',
            'ANANAS_COMOSUS', 'MANGIFERA_FOETIDA', 'THEOBROMA_CACAO', 'COFFEA_ARABICA', 'SACCHARUM_SPONTANEUM', 'GOSSYPIUM_HIRSUTUM', 'HELIANTHUS_TUBEROSUS', 'BRASSICA_NAPUS', 'ELAEIS_OLEIFERA', 'COCOS_CAPITATA',
            'PHASEOLUS_LUNATUS', 'GLYCINE_MAX', 'SECALE_CEREALE', 'SORGHUM_BICOLOR', 'MEDICAGO_SATIVA', 'TRIFOLIUM_PRATENSE', 'LOLIUM_MULTIFLORUM', 'FESTUCA_RUBRA', 'DACTYLIS_GLOMERATA', 'PENNISETUM_PURPUREUM',
            'SOLANUM_TUBEROSUM', 'PHASEOLUS_VULGARIS', 'TRITICUM_AESTIVUM', 'ORYZA_SATIVA', 'GLYCINE_SOJA', 'HORDEUM_VULGARE', 'AVENA_SATIVA', 'SECALE_MONTANUM', 'SORGHUM_SUDANENSE', 'ZEA_MEXICANA',
            'MALUS_DOMESTICA', 'PYRUS_PYRIFOLIA', 'VITIS_LABRUSCA', 'PRUNUS_PERSICA', 'PRUNUS_DULCIS', 'CITRUS_SINENSIS', 'CITRUS_LIMON', 'FRAGARIA_ANANASSA', 'MUSA_ACUMINATA', 'PERSEA_GRATISSIMA',
            'VANILLA_PLANIFOLIA', 'CINNAMOMUM_VERUM', 'PIPER_NIGRUM', 'ZINGIBER_OFFICINALE', 'CURCUMA_LONGA', 'CROCUS_SATIVUS', 'ELETTARIA_CARDAMOMUM', 'SYZYGIUM_AROMATICUM', 'MYRISTICA_FRAGRANS', 'PIMPINELLA_ANISUM'
        ],
        experto: [
            'CRISPR_CAS9', 'TRANSCRIPTOMICA', 'INTERACTOMICA', 'FLUXOMICA', 'FENOMICA', 'QUIMIOMETRIA', 'BIOESTADISTICA', 'GEOESTADISTICA', 'ECONOMETRIA', 'PSICOMETRIA',
            'MEDICAGO_LUPULINA', 'TRIFOLIUM_REPENS', 'LOLIUM_PERENNE', 'FESTUCA_ARUNDINACEA', 'DACTYLIS_HISPANICA', 'PENNISETUM_CLANDESTINUM', 'BRACHIARIA_BRIZANTHA', 'PANICUM_MAXIMUM', 'CYNODON_PLECTOSTACHYUS', 'SORGHUM_HALEPENSE',
            'AGAVE_TEQUILANA', 'OPUNTIA_STREPTACANTHA', 'RICINUS_ZANZIBARENSIS', 'LINUM_BIENNE', 'CANNABIS_INDICA', 'NICOTIANA_TABACUM', 'GOSSYPIUM_BARBADENSE', 'ELAEIS_MELANOCOCCA', 'COCOS_SCHIZOPHYLLA', 'PHOENIX_DACTYLIFERA',
            'MICROPROPAGACION', 'BIOINFORMATICA', 'GENOMICA', 'PROTEOMICA', 'METABOLOMICA', 'EPIGENETICA', 'NANOTECNOLOGIA', 'BIOREMEDIACION', 'FITOREMEDIACION', 'XENOBIOTICO',
            'FOTOSINTESIS', 'HIDROPONIA', 'TRANSGENICO', 'METEOROLOGIA', 'CLIMATOLOGIA', 'GEOLOGIA', 'EDAFOLOGIA', 'CARTOGRAFIA', 'SOCIOLOGIA', 'ECONOMIA',
            'EPISTEMOLOGIA', 'PARADIGMA', 'ONTOLOGIA', 'METODOLOGIA', 'HERMENEUTICA', 'DIALECTICA', 'FENOMENOLOGIA', 'ESTRUCTURALISMO', 'FUNCIONALISMO', 'PRAGMATISMO',
            'CUMINUM_CYMINUM', 'ORIGANUM_VULGARE', 'THYMUS_VULGARIS', 'ROSMARINUS_OFFICINALIS', 'OCIMUM_BASILICUM', 'MENTHA_PIPERITA', 'MENTHA_SPICATA', 'FOENICULUM_VULGARE', 'CORIANDRUM_SATIVUM', 'PETROSELINUM_CRISPUM'
        ]
    }
};

const ADVENTURE_POOLS = {
    facil: [
        'MAIZ', 'TRIGO', 'ARROZ', 'PAPA', 'TOMATE', 'LECHUGA', 'ZANAHORIA', 'CEBOLLA', 'AJO', 'CHILE',
        'FRIJOL', 'SOYA', 'AVENA', 'CEBADA', 'CENTENO', 'SORGO', 'MIJO', 'ALFALFA', 'TREBOL', 'PASTO',
        'VACA', 'CERDO', 'POLLO', 'PAVO', 'PATO', 'GANSO', 'CABRA', 'OVEJA', 'CABALLO', 'BURRO',
        'MANZANA', 'PERA', 'UVA', 'FRESA', 'MORA', 'PIÑA', 'SANDIA', 'MELON', 'PLATANO', 'MANGO',
        'AGUA', 'SOL', 'TIERRA', 'LLUVIA', 'VIENTO', 'NUBE', 'RIO', 'LAGO', 'POZO', 'CANAL',
        'SEMILLA', 'RAIZ', 'TALLO', 'HOJA', 'FLOR', 'FRUTO', 'POLEN', 'RAMA', 'TRONCO', 'BOSQUE',
        'SELVA', 'CAMPO', 'GRANJA', 'HUERTO', 'JARDIN', 'CERCA', 'REJA', 'PALA', 'PICO', 'AZADA',
        'SACO', 'CRIBA', 'CUBO', 'JARRA', 'SOGA', 'VILLA', 'PUEBLO', 'RANCH', 'ALDEA', 'MONTE',
        'LIMON', 'NARANJA', 'MANDARINA', 'POMELO', 'DURAZNO', 'CIRUELA', 'CEREZA', 'ALBARICOQUE', 'HIGO', 'DATIL',
        'OLIVO', 'NOGAL', 'ALMENDRO', 'CASTAÑO', 'AVELLANO', 'PISTACHO', 'PINO', 'ROBLE', 'ENCINA', 'HAYA'
    ],
    medio: [
        'ARADO', 'RASTRA', 'SEMBRADORA', 'COSECHADORA', 'FUMIGADORA', 'FERTILIZADORA', 'TRACTOR', 'REMOLQUE', 'SISTEMA', 'RIEGO',
        'GOTA', 'ASPERSION', 'GRAVEDAD', 'BOMBEO', 'TUBERIA', 'VALVULA', 'FILTRO', 'TANQUE', 'PRESA', 'DIQUE',
        'INVERNADERO', 'MACROTUNEL', 'MICROTUNEL', 'MALLA', 'SOMBRA', 'PLASTICO', 'ACOLCHADO', 'SUSTRATO', 'HIDROPONIA', 'AEROPONIA',
        'COMPOSTA', 'LOMBRICULTURA', 'BOCASHI', 'BIOL', 'PURIN', 'ESTIERCOL', 'GUANO', 'HUMUS', 'LIXIVIADO', 'RESIDUO',
        'PODA', 'RALEO', 'DESHIERBE', 'APORQUE', 'TUTORADO', 'COSECHA', 'EMPAQUE', 'TRANSPORTE', 'ALMACEN', 'VENTA',
        'MOLINO', 'SILO', 'CORRAL', 'ESTABLO', 'GALLINERO', 'PORQUERIZA', 'APEROS', 'BODEGA', 'GALPON', 'HERRAMIENTA',
        'MOTOCULTOR', 'DESBROZADORA', 'MOTOSIERRA', 'TIJERAS', 'SERRUCHO', 'MARTILLO', 'CLAVO', 'ALAMBRE', 'PESTICIDA', 'ABONO',
        'FERTILIZANTE', 'PESTICIDA', 'FUNGICIDA', 'HERBICIDA', 'ACARICIDA', 'NEMATICIDA', 'BACTERICIDA', 'VIRICIDA', 'ADHERENTE', 'SURFACTANTE',
        'INJERTO', 'ACODO', 'ESTACA', 'YEMA', 'PORTAINJERTO', 'PATRON', 'VARIEDAD', 'HIBRIDO', 'CULTIVAR', 'CLON',
        'MULCH', 'COBERTURA', 'BANCAL', 'CAMELLON', 'SURCO', 'HILERA', 'MARCO', 'DENSIDAD', 'ESPACIAMIENTO', 'DISTANCIA'
    ],
    dificil: [
        'AGRONOMIA', 'EDAFOLOGIA', 'FITOPATOLOGIA', 'ENTOMOLOGIA', 'GENETICA', 'FISIOLOGIA', 'BIOQUIMICA', 'MICROBIOLOGIA', 'ECOLOGIA', 'METEOROLOGIA',
        'FOTOSINTESIS', 'RESPIRACION', 'TRANSPIRACION', 'NUTRICION', 'ABSORCION', 'TRANSLOCACION', 'METABOLISMO', 'ENZIMA', 'HORMONA', 'AUXINA',
        'GIBERELINA', 'CITOCININA', 'ETILENO', 'ABSCISICO', 'FLORACION', 'FRUCTIFICACION', 'MADURACION', 'SENESCENCIA', 'ABSCISION', 'DORMANCIA',
        'SALINIDAD', 'ACIDEZ', 'ALCALINIDAD', 'COMPACTACION', 'EROSION', 'LIXIVIACION', 'VOLATILIZACION', 'DENITRIFICACION', 'EUTROFIZACION', 'CONTAMINACION',
        'PESTICIDA', 'HERBICIDA', 'FUNGICIDA', 'INSECTICIDA', 'ACARICIDA', 'NEMATICIDA', 'BACTERICIDA', 'VIRICIDA', 'ADHERENTE', 'SURFACTANTE',
        'AGROECOLOGIA', 'PERMACULTURA', 'SILVICULTURA', 'AGROFORESTERIA', 'BIOTECNOLOGIA', 'GENOMICA', 'PROTEOMICA', 'METABOLOMICA', 'BIOINFORMATICA', 'NANOTECNOLOGIA',
        'HIDROLOGIA', 'GEOLOGIA', 'TOPOGRAFIA', 'CARTOGRAFIA', 'GEODESIA', 'FOTOGRAMETRIA', 'TELEDETECCION', 'SIG', 'GPS', 'DRON',
        'ROBOTICA', 'DOMOTICA', 'AUTOMATIZACION', 'SENSORES', 'TELEMETRIA', 'BIG_DATA', 'IA', 'BLOCKCHAIN', 'TRAZABILIDAD', 'INOCUIDAD',
        'FENOLOGIA', 'VERNALIZACION', 'FOTOPERIODO', 'TERMOPERIODICIDAD', 'ESTRATIFICACION', 'LATENCIA', 'QUIESCENCIA', 'IMBIBICION', 'ESCARIFICACION', 'VIABILIDAD'
    ],
    experto: [
        'ZEA_MAYS', 'SOLANUM_TUBEROSUM', 'PHASEOLUS_VULGARIS', 'TRITICUM_AESTIVUM', 'ORYZA_SATIVA', 'GLYCINE_MAX', 'HORDEUM_VULGARE', 'AVENA_SATIVA', 'SECALE_CEREALE', 'SORGHUM_BICOLOR',
        'SOLANUM_LYCOPERSICUM', 'CAPSICUM_ANNUUM', 'ALLIUM_CEPA', 'ALLIUM_SATIVUM', 'DAUCUS_CAROTA', 'LACTUCA_SATIVA', 'BRASSICA_OLERACEA', 'CUCUMIS_SATIVUS', 'CUCURBITA_PEPO', 'CITRULLUS_LANATUS',
        'MUSA_PARADISIACA', 'ANANAS_COMOSUS', 'MANGIFERA_INDICA', 'CITRUS_SINENSIS', 'CITRUS_LIMON', 'VITIS_VINIFERA', 'FRAGARIA_ANANASSA', 'RUBUS_IDAEUS', 'VACCINIUM_CORYMBOSUM', 'PERSEA_AMERICANA',
        'COFFEA_ARABICA', 'THEOBROMA_CACAO', 'SACCHARUM_OFFICINARUM', 'GOSSYPIUM_HIRSUTUM', 'HELIANTHUS_ANNUUS', 'BRASSICA_NAPUS', 'ELAEIS_GUINEENSIS', 'COCOS_NUCIFERA', 'AGAVE_TEQUILANA', 'OPUNTIA_FICUS_INDICA',
        'MEDICAGO_SATIVA', 'TRIFOLIUM_REPENS', 'LOLIUM_PERENNE', 'FESTUCA_ARUNDINACEA', 'DACTYLIS_GLOMERATA', 'PENNISETUM_CLANDESTINUM', 'BRACHIARIA_BRIZANTHA', 'PANICUM_MAXIMUM', 'CYNODON_DACTYLON', 'SORGHUM_HALEPENSE',
        'PHASEOLUS_LUNATUS', 'GLYCINE_SOJA', 'HORDEUM_SPONTANEUM', 'AVENA_BYZANTINA', 'SECALE_MONTANUM', 'SORGHUM_SUDANENSE', 'ZEA_MEXICANA', 'MALUS_DOMESTICA', 'PYRUS_PYRIFOLIA', 'VITIS_LABRUSCA',
        'PRUNUS_PERSICA', 'PRUNUS_DULCIS', 'CITRUS_AURANTIUM', 'FRAGARIA_VESCA', 'PRUNUS_AVIUM', 'MUSA_ACUMINATA', 'PERSEA_GRATISSIMA', 'MANGIFERA_FOETIDA', 'THEOBROMA_BICOLOR', 'SACCHARUM_SPONTANEUM',
        'GOSSYPIUM_BARBADENSE', 'HELIANTHUS_TUBEROSUS', 'BRASSICA_RAPA', 'ELAEIS_OLEIFERA', 'COCOS_CAPITATA', 'AGAVE_AMERICANA', 'OPUNTIA_STREPTACANTHA', 'RICINUS_COMMUNIS', 'LINUM_USITATISSIMUM', 'CANNABIS_SATIVA',
        'CITRUS_RETICULATA', 'CITRUS_PARADISI', 'PRUNUS_DOMESTICA', 'PRUNUS_ARMENIACA', 'FICUS_CARICA', 'PHOENIX_DACTYLIFERA', 'OLEA_EUROPAEA', 'JUGLANS_REGIA', 'PRUNUS_AMYGDALUS', 'CASTANEA_SATIVA'
    ]
};

const LEVEL_CONFIGS = {
    // Educational & Adventure use the same difficulty keys now
    facil: { gridSize: 8, wordCount: 6, directions: ['horizontal', 'vertical'] },
    medio: { gridSize: 10, wordCount: 8, directions: ['horizontal', 'vertical', 'diagonal'] },
    dificil: { gridSize: 12, wordCount: 10, directions: ['horizontal', 'vertical', 'diagonal', 'reverse'] },
    experto: { gridSize: 15, wordCount: 12, directions: ['horizontal', 'vertical', 'diagonal', 'reverse', 'diagonal-reverse'] }
};

function getLevelData(difficulty, levelNumber, mode = 'educational', academicLevel = 'primaria') {
    const config = LEVEL_CONFIGS[difficulty];
    let fullPool = [];

    // 1. Obtener el banco de palabras completo
    if (mode === 'adventure') {
        fullPool = ADVENTURE_POOLS[difficulty] || [];
    } else {
        // Validación de seguridad por si el nivel académico no existe
        if (EDUCATIONAL_WORD_BANK[academicLevel] && EDUCATIONAL_WORD_BANK[academicLevel][difficulty]) {
            fullPool = EDUCATIONAL_WORD_BANK[academicLevel][difficulty];
        } else {
            console.error(`Pool no encontrado: ${academicLevel} - ${difficulty}`);
            fullPool = ['ERROR'];
        }
    }

    // 2. Clave única para guardar progreso en LocalStorage
    // Ejemplo: 'history_adventure_dificil' o 'history_primaria_facil'
    const storageKey = mode === 'adventure'
        ? `agroletras_history_${mode}_${difficulty}`
        : `agroletras_history_${academicLevel}_${difficulty}`;

    // 3. Obtener historial de palabras ya jugadas
    let playedWords = JSON.parse(localStorage.getItem(storageKey) || '[]');

    // 4. Filtrar el pool para dejar solo las NO jugadas
    let availableWords = fullPool.filter(word => !playedWords.includes(word));

    // 5. Lógica de "Baraja Agotada": Si no alcanzan las palabras, reiniciamos el historial
    if (availableWords.length < config.wordCount) {
        console.log(`Pool agotado para ${storageKey}. Reiniciando ciclo.`);
        playedWords = []; // Limpiamos memoria
        availableWords = [...fullPool]; // Restauramos todo el pool
        localStorage.setItem(storageKey, JSON.stringify([]));
    }

    // 6. Selección Aleatoria de las palabras disponibles
    // Usamos Math.random() real para que sea impredecible y no dependa del número de nivel fijo
    const shuffled = [...availableWords].sort(() => 0.5 - Math.random());
    const selectedWords = shuffled.slice(0, config.wordCount);

    // 7. Guardar las nuevas palabras en el historial para no repetirlas la próxima vez
    const newHistory = [...playedWords, ...selectedWords];
    localStorage.setItem(storageKey, JSON.stringify(newHistory));

    return {
        gridSize: config.gridSize,
        words: selectedWords,
        directions: config.directions,
        levelNumber: levelNumber,
        difficulty: difficulty,
        mode: mode,
        academicLevel: academicLevel
    };
}

// Lógica de Generación Dinámica para Modo Clasificación
function getRankedLevelData() {
    // 1. Recopilar palabras de todos los pools
    const allWords = {
        facil: [],
        medio: [],
        dificil: [],
        experto: []
    };

    // Usar EDUCATIONAL_WORD_BANK como fuente principal (o mezclar ambos si se desea)
    // Aquí usaremos una mezcla plana de todos los niveles académicos para tener variedad
    Object.values(EDUCATIONAL_WORD_BANK).forEach(academicLevel => {
        if (academicLevel.facil) allWords.facil.push(...academicLevel.facil);
        if (academicLevel.medio) allWords.medio.push(...academicLevel.medio);
        if (academicLevel.dificil) allWords.dificil.push(...academicLevel.dificil);
        if (academicLevel.experto) allWords.experto.push(...academicLevel.experto);
    });

    const categories = ['facil', 'medio', 'dificil', 'experto'];
    const selectedWords = [];
    const maxWords = Math.floor(Math.random() * 3) + 10; // 10 a 12 palabras

    // 2. Selección Aleatoria de categoría para cada slot
    const rng = new SeededRandom(Date.now()); // Usar tiempo real para aleatoriedad en cada juego

    for (let i = 0; i < maxWords; i++) {
        const catIndex = Math.floor(rng.next() * categories.length);
        const category = categories[catIndex];
        const wordPool = allWords[category];

        if (wordPool.length > 0) {
            const wordIndex = Math.floor(rng.next() * wordPool.length);
            const word = wordPool[wordIndex];

            // Evitar duplicados
            if (!selectedWords.some(w => w.text === word)) {
                selectedWords.push({ text: word, difficulty: category });
            } else {
                i--; // Reintentar
            }
        }
    }

    // 3. Determinar Grid Size basado en Jerarquía
    let maxDifficulty = 'facil'; // Default
    const difficultyRank = { 'facil': 1, 'medio': 2, 'dificil': 3, 'experto': 4 };

    selectedWords.forEach(w => {
        if (difficultyRank[w.difficulty] > difficultyRank[maxDifficulty]) {
            maxDifficulty = w.difficulty;
        }
    });

    let gridSize = 8;
    if (maxDifficulty === 'experto') gridSize = 15;
    else if (maxDifficulty === 'dificil') gridSize = 12;
    else if (maxDifficulty === 'medio') gridSize = 10;
    else gridSize = 8; // Facil

    // Mapeo de config basado en nivel jerárquico (direcciones permitidas)
    const configBase = LEVEL_CONFIGS[maxDifficulty];

    return {
        gridSize: gridSize,
        words: selectedWords.map(w => w.text), // Solo pasar los textos
        directions: configBase.directions,
        levelNumber: 'RANKED',
        difficulty: maxDifficulty, // Para referencia
        mode: 'ranking'
    };
}

